[template]
cargo_generate_version = ">=0.10.0"

[placeholders.bevy]
type = "bool"
prompt = "Include Bevy CI support?"
default = true

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]
